name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - master  # or your default branch name

jobs:
  deploy:
    environment: aws_archi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # Use the latest LTS version of Node.js

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        run: npm ci  # Use npm ci for clean, repeatable installs

      - name: Build project
        run: npm run build

      - name: AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # replace with your AWS region

      - name: Delete existing files in S3
        run: |
          aws s3 rm s3://${{ secrets.S3_BUCKET }} --recursive

      - name: Upload to S3
        run: |
          aws s3 sync dist s3://${{ secrets.S3_BUCKET }}

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_2 }} --paths "/*"